version: "3.9"
services:
  redis:
    image: redis
    ports: 
      - "6379:6379"
    container_name: redis
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: neteast
      MYSQL_INITDB_SKIP_TZINFO: "true"
  mycq:
    image: youmuu/mycq
    container_name: mycq
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
